# Generated by Django 2.2.6 on 2019-10-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('store_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('logo_url', models.CharField(max_length=1000)),
                ('registered_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('picture_url', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=30)),
                ('registered_time', models.CharField(max_length=50)),
                ('stores', models.CharField(max_length=11)),
                ('status', models.CharField(max_length=20)),
                ('fcm_token', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('logo_url', models.CharField(max_length=1000)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('registered_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
