# Generated by Django 2.2.6 on 2019-10-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=11)),
                ('member_id', models.CharField(max_length=11)),
                ('brand_id', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=50)),
                ('picture_url', models.CharField(max_length=1000)),
                ('category', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=11)),
                ('new_price', models.CharField(max_length=11)),
                ('unit', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=2000)),
                ('registered_time', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('likes', models.CharField(max_length=11)),
                ('isLiked', models.CharField(max_length=20)),
                ('ratings', models.CharField(max_length=11)),
            ],
        ),
    ]
