# Generated by Django 2.2.6 on 2019-10-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=11)),
                ('picture_url', models.CharField(max_length=1000)),
            ],
        ),
    ]
