# Generated by Django 2.2.6 on 2019-10-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orion', '0003_productpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=11)),
                ('bank_number', models.CharField(max_length=30)),
                ('routing_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('postal_code', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('ssn_last4', models.CharField(max_length=30)),
                ('birth_date', models.CharField(max_length=11)),
                ('birth_month', models.CharField(max_length=11)),
                ('birth_year', models.CharField(max_length=11)),
                ('registered_time', models.CharField(max_length=50)),
                ('acc_id', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
